export const appsettings = {
  apiUrl: "https://localhost:7101/api/",
  //apiUrl: "https://sanuchiha-001-site1.ctempurl.com/api/",
  escenarios: [
    "1. Domination",
    "2. To the Death!",
    "3. Hold Ground",
    "4. Lords of Battle",
    "5. Reconnoitre",
    "6. A Clash by Moonlight",
    "7. Seize the Prize",
    "8. Contest of Champions",
    "9. Capture and Control",
    "10. Heirloom of Ages Past",
    "11. Fog of War",
    "12. Storm the Camp",
    "13. Command the Battlefield",
    "14. Retrieval",
    "15. Breakthrough",
    "16. Destroy the Supplies",
    "17. Divide And Conquer",
    "18. Assassination",
  ],

  ejercitos: [
    "Angmar",
    "Army of Lake-town",
    "Army of Thrór",
    "Arnor",
    "Azog´s Hunters",
    "Azog´s Legion",
    "Barad-Dûr",
    "Corsairs of Umbar",
    "Dark Denezins of Mirkwood",
    "Dark Powers of Dol Guldor",
    "Desolator of the North",
    "Erebor Reclaimed",
    "Fangorn",
    "Far Harad",
    "Garrison of Dale",
    "Goblin-Town",
    "Halls of Thranduil",
    "Isengard",
    "Lothlórien",
    "Minas Tirith",
    "Mordor",
    "Moria",
    "Númenor",
    "Radagast´s Alliance",
    "Rivendell",
    "Rohan",
    "Sharkey´s Rogues",
    "Survivors of Lake-town",
    "The Dead of Dunharrow",
    "The Easterlings",
    "The Fellowship",
    "The Fiefdoms",
    "The Iron Hills",
    "The Kingdom of Khazad-Dûm",
    "The Kingdom of Moria",
    "The Misty Mountains",
    "The Rangers",
    "The Serpent Horde",
    "The Shire",
    "The Trolls",
    "The White Council",
    "Thorin´s Company",
    "Variags of Khand",
    "Wildmen of Drúadan",
    "The Army of Dale",
    "Defenders of Erebor",
    "The Beornings",
    "Host of the Dragon Emperor",
    "Fell Beings of Mirkwood",
    "Assault on Lothlórie",
    "Rangers of Mirkwood",
    "The Vanquishers of the Necromancer",
    "Pits of Dol Guldur",
    "Rise of the Necromancer",
    "Rangers of Ithilien",
    "The Grey Company",
    "The Return of the King",
    "The Riders of Théoden",
    "The Men of the West",
    "The Army of Gothmog",
    "Grand Army of the South",
    "The Black Gate Opens",
    "Breaking of the Fellowship",
    "Lurtz’s Scouts",
    "Depths of Moria",
    "The Black Riders",
    "Cirith Ungol",
    "Defenders of the Shire",
    "The Chief’s Ruffians",
    "Defenders of Helm’s Deep",
    "Théodred’s Guard",
    "Riders of Éomer",
    "Paths of the Drúadan",
    "Uglúk’s Scouts",
    "Wolves of Isengard",
    "Assault upon Helm’s Deep",
    "Army of Dunland",
    "Helm’s Guard",
    "Battle of Fornost",
    "Army of Arnor",
    "Host of the Witch-King",
    "Army of Carn Dûm",
    "Wolf pack of Angmar",
    "Arathorn´s Stand",
    "Buhrdûr´s Horde",
  ],
};
