export const appsettings = {
  //apiUrl: "https://localhost:7101/api/",
  apiUrl: "https://sanuchiha-001-site1.ctempurl.com/api/",

  escenarios: [
    "1. Domination",
    "2. To the Death!",
    "3. Hold Ground",
    "4. Lords of Battle",
    "5. Reconnoitre",
    "6. A Clash by Moonlight",
    "7. Seize the Prize",
    "8. Contest of Champions",
    "9. Capture and Control",
    "10. Heirloom of Ages Past",
    "11. Fog of War",
    "12. Storm the Camp",
    "13. Command the Battlefield",
    "14. Retrieval",
    "15. Breakthrough",
    "16. Destroy the Supplies",
    "17. Divide And Conquer",
    "18. Assassination",
  ],

  armies: [
    // Good
    { name: "Arathorn's Stand", band: "good" },
    { name: "Army of Arnor", band: "good" },
    { name: "Army of Lake-town", band: "good" },
    { name: "Army of Thrór", band: "good" },
    { name: "Battle of Fornost", band: "good" },
    { name: "Breaking of the Fellowship", band: "good" },
    { name: "Defenders of Erebor", band: "good" },
    { name: "Defenders of Helm’s Deep", band: "good" },
    { name: "Defenders of the Shire", band: "good" },
    { name: "Erebor Reclaimed", band: "good" },
    { name: "Fangorn", band: "good" },
    { name: "Garrison of Dale", band: "good" },
    { name: "Halls of Thranduil", band: "good" },
    { name: "Helm’s Guard", band: "good" },
    { name: "Kingdom of Khazad-Dûm", band: "good" },
    { name: "Kingdom of Moria", band: "good" },
    { name: "Lothlórien", band: "good" },
    { name: "Minas Tirith", band: "good" },
    { name: "Misty Mountains", band: "good" },
    { name: "Númenor", band: "good" },
    { name: "Paths of the Drúadan", band: "good" },
    { name: "Radagast's Alliance", band: "good" },
    { name: "Rangers of Ithilien", band: "good" },
    { name: "Rangers of Mirkwood", band: "good" },
    { name: "Return of the King", band: "good" },
    { name: "Riders of Éomer", band: "good" },
    { name: "Riders of Théoden", band: "good" },
    { name: "Rivendell", band: "good" },
    { name: "Rohan", band: "good" },
    { name: "Shire", band: "good" },
    { name: "Survivors of Lake-town", band: "good" },
    { name: "The Beornings", band: "good" },
    { name: "The Dead of Dunharrow", band: "good" },
    { name: "The Fellowship", band: "good" },
    { name: "The Fiefdoms", band: "good" },
    { name: "The Grey Company", band: "good" },
    { name: "The Iron Hills", band: "good" },
    { name: "The Rangers", band: "good" },
    { name: "The Vanquishers of the Necromancer", band: "good" },
    { name: "The White Council", band: "good" },
    { name: "Théodred’s Guard", band: "good" },
    { name: "Thorin's Company", band: "good" },
    { name: "Wildmen of Drúadan", band: "good" },

    //Evil
    { name: "Angmar", band: "evil" },
    { name: "Army of Carn Dûm", band: "evil" },
    { name: "Army of Gothmog", band: "evil" },
    { name: "Army of Dunland", band: "evil" },
    { name: "Assault on Lothlórien", band: "evil" },
    { name: "Assault upon Helm’s Deep", band: "evil" },
    { name: "Azog's Hunters", band: "evil" },
    { name: "Azog's Legion", band: "evil" },
    { name: "Barad-Dûr", band: "evil" },
    { name: "Black Gate Opens", band: "evil" },
    { name: "Buhrdûr's Horde", band: "evil" },
    { name: "Chief’s Ruffians", band: "evil" },
    { name: "Cirith Ungol", band: "evil" },
    { name: "Corsairs of Umbar", band: "evil" },
    { name: "Dark Denizens of Mirkwood", band: "evil" },
    { name: "Dark Powers of Dol Guldor", band: "evil" },
    { name: "Desolator of the North", band: "evil" },
    { name: "Depths of Moria", band: "evil" },
    { name: "Fell Beings of Mirkwood", band: "evil" },
    { name: "Goblin-Town", band: "evil" },
    { name: "Grand Army of the South", band: "evil" },
    { name: "Host of the Dragon Emperor", band: "evil" },
    { name: "Host of the Witch-King", band: "evil" },
    { name: "Isengard", band: "evil" },
    { name: "Lurtz’s Scouts", band: "evil" },
    { name: "Mordor", band: "evil" },
    { name: "Moria", band: "evil" },
    { name: "Pits of Dol Guldur", band: "evil" },
    { name: "Rise of the Necromancer", band: "evil" },
    { name: "Serpent Horde", band: "evil" },
    { name: "Sharkey's Rogues", band: "evil" },
    { name: "The Black Riders", band: "evil" },
    { name: "The Easterlings", band: "evil" },
    { name: "The Trolls", band: "evil" },
    { name: "Uglúk’s Scouts", band: "evil" },
    { name: "Variags of Khand", band: "evil" },
    { name: "Wolf pack of Angmar", band: "evil" },
    { name: "Wolves of Isengard", band: "evil" },
  ],
};
