export const appsettings = {
  //apiUrl: "https://localhost:7101/api/",
  apiUrl: "https://sanuchiha-001-site1.ctempurl.com/api/",

  escenarios: [
    "1. Domination",
    "2. To the Death!",
    "3. Hold Ground",
    "4. Lords of Battle",
    "5. Reconnoitre",
    "6. A Clash by Moonlight",
    "7. Seize the Prize",
    "8. Contest of Champions",
    "9. Capture and Control",
    "10. Heirloom of Ages Past",
    "11. Fog of War",
    "12. Storm the Camp",
    "13. Command the Battlefield",
    "14. Retrieval",
    "15. Breakthrough",
    "16. Destroy the Supplies",
    "17. Divide And Conquer",
    "18. Assassination",
  ],

  armies: [
    // Good
    // Facciones de Luz (Good), ordenadas alfabéticamente
    { name: "Atop the Wall", band: "good" },
    { name: "Army of Edoras", band: "good" },
    { name: "Breaking of the Fellowship", band: "good" },
    { name: "Defenders of Helm's Deep", band: "good" },
    { name: "Defenders of the Hornburg", band: "good" },
    { name: "Fangorn", band: "good" },
    { name: "Garrison of Ithilien", band: "good" },
    { name: "Kingdom of Rohan", band: "good" },
    { name: "Lindon", band: "good" },
    { name: "Lothlorien", band: "good" },
    { name: "Men of the West", band: "good" },
    { name: "Minas Tirith", band: "good" },
    { name: "Reclamation of Osgiliath", band: "good" },
    { name: "Return of the King", band: "good" },
    { name: "Ride Out", band: "good" },
    { name: "Riders of Eomer", band: "good" },
    { name: "Rivendell", band: "good" },
    { name: "Road to Helm's Deep", band: "good" },
    { name: "Road to Rivendell", band: "good" },
    { name: "The Eagles", band: "good" },
    { name: "The Fellowship", band: "good" },
    { name: "The Last Alliance", band: "good" },
    { name: "The Shire", band: "good" },

    { name: "Army of Lake-town", band: "good" },
    { name: "Army of Thrór", band: "good" },
    { name: "Battle of the Five Armies", band: "good" },
    { name: "Defenders of Dale", band: "good" },
    { name: "Erebor Reclaimed", band: "good" },
    { name: "Halls of Thranduil", band: "good" },
    { name: "Iron Hills", band: "good" },
    { name: "Mirkwood Rangers", band: "good" },
    { name: "Radagast's Alliance", band: "good" },
    { name: "Rivendell", band: "good" },
    { name: "Survivors of Lake-town", band: "good" },
    { name: "The White Council", band: "good" },
    { name: "Thorin's Company", band: "good" },

    { name: "Arnor", band: "good" },
    { name: "Arathorn’s Stand", band: "good" },
    { name: "Battle of Fornost", band: "good" },

    // Facciones de Oscuridad (Evil), ordenadas alfabéticamente
    { name: "Army of Gundabad", band: "evil" },
    { name: "Army of Thror", band: "evil" },
    { name: "Army of the White Hand", band: "evil" },
    { name: "Assault Upon Helm's Deep", band: "evil" },
    { name: "Azog's Hunters", band: "evil" },
    { name: "Barad-Dur", band: "evil" },
    { name: "Cirith Ungol", band: "evil" },
    { name: "Legions of Mordor", band: "evil" },
    { name: "Lurtz's Scouts", band: "evil" },
    { name: "Minas Morgul", band: "evil" },
    { name: "Muster of Isengard", band: "evil" },
    { name: "The Black Gate Opens", band: "evil" },
    { name: "The Black Riders", band: "evil" },
    { name: "The Iron Hills", band: "evil" },
    { name: "Ugluk's Scouts", band: "evil" },
    { name: "Usurpers of Edoras", band: "evil" },
    { name: "Wolves of Isengard", band: "evil" },

    { name: "Army of Gundabad", band: "evil" },
    { name: "Azog's Hunters", band: "evil" },
    { name: "Dol Guldur", band: "evil" },
    { name: "Goblin-town", band: "evil" },
    { name: "The Desolator of the North", band: "evil" },
    { name: "The Rise of the Necromancer", band: "evil" },
    { name: "The Three Trolls", band: "evil" },

    { name: "Army of Carn Dûm", band: "evil" },
    { name: "Buhrdûr’s Horde", band: "evil" },
    { name: "Host of the Witch-king", band: "evil" },
    { name: "Shadows of Angmar", band: "evil" },
    { name: "Wolf Pack of Angmar", band: "evil" },
  ],
};
